env:
  browser: true
  es6: true
  webextensions: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-trailing-spaces: warn
  no-unused-vars: warn
  prefer-const: warn
  no-var: error
parserOptions:
  ecmaVersion: 2017
  sourceType: module
